---
# Inventory for SUSE AI Stack with Kagent Add-on
all:
  children:
    suse_ai_cluster:
      hosts:
        suse-ai-master:
          ansible_host: "{{ suse_ai_master_ip | default('192.168.1.100') }}"
          ansible_user: "{{ ansible_user | default('suse') }}"
          ansible_ssh_private_key_file: "{{ ssh_private_key | default('~/.ssh/id_rsa') }}"
          node_role: master
        suse-ai-worker-1:
          ansible_host: "{{ suse_ai_worker1_ip | default('192.168.1.101') }}"
          ansible_user: "{{ ansible_user | default('suse') }}"
          ansible_ssh_private_key_file: "{{ ssh_private_key | default('~/.ssh/id_rsa') }}"
          node_role: worker
        suse-ai-worker-2:
          ansible_host: "{{ suse_ai_worker2_ip | default('192.168.1.102') }}"
          ansible_user: "{{ ansible_user | default('suse') }}"
          ansible_ssh_private_key_file: "{{ ssh_private_key | default('~/.ssh/id_rsa') }}"
          node_role: worker
      vars:
        ansible_python_interpreter: /usr/bin/python3
        cluster_name: "suse-ai-cluster"
        suse_ai_master_ip: "{{ hostvars['suse-ai-master']['ansible_host'] }}"
