---
all:
  children:
    k3s_cluster:
      hosts:
        k3s-master:
          ansible_host: "{{ k3s_master_ip | default('192.168.1.100') }}"
          ansible_user: "{{ ansible_user | default('suse') }}"
          ansible_ssh_private_key_file: "{{ ssh_private_key | default('~/.ssh/id_rsa') }}"
          node_role: master
        k3s-worker-1:
          ansible_host: "{{ k3s_worker1_ip | default('192.168.1.101') }}"
          ansible_user: "{{ ansible_user | default('suse') }}"
          ansible_ssh_private_key_file: "{{ ssh_private_key | default('~/.ssh/id_rsa') }}"
          node_role: worker
        k3s-worker-2:
          ansible_host: "{{ k3s_worker2_ip | default('192.168.1.102') }}"
          ansible_user: "{{ ansible_user | default('suse') }}"
          ansible_ssh_private_key_file: "{{ ssh_private_key | default('~/.ssh/id_rsa') }}"
          node_role: worker
      vars:
        ansible_python_interpreter: /usr/bin/python3
        cluster_name: "kagent-cluster"
        k3s_version: "v1.28.5+k3s1"
        k3s_token: "{{ k3s_token | default('kagent-token-12345') }}"
        k3s_master_ip: "{{ hostvars['k3s-master']['ansible_host'] }}"
