---
# Single-node K3s cluster for demo purposes
all:
  children:
    k3s_cluster:
      hosts:
        k3s-demo:
          ansible_host: "{{ k3s_demo_ip | default('192.168.1.100') }}"
          ansible_user: "{{ ansible_user | default('suse') }}"
          ansible_ssh_private_key_file: "{{ ssh_private_key | default('~/.ssh/id_rsa') }}"
          node_role: master
      vars:
        ansible_python_interpreter: /usr/bin/python3
        cluster_name: "kagent-demo-cluster"
        k3s_version: "v1.28.5+k3s1"
        k3s_token: "{{ k3s_token | default('kagent-demo-token-12345') }}"
        k3s_demo_ip: "{{ hostvars['k3s-demo']['ansible_host'] }}"
        # Single node specific settings
        k3s_disable_components:
          - "traefik"
          - "servicelb"
          - "local-storage"
        # Resource optimizations for single node
        kagent_resources:
          requests:
            memory: "1Gi"
            cpu: "0.5"
          limits:
            memory: "2Gi"
            cpu: "1"
        ollama_resources:
          requests:
            memory: "2Gi"
            cpu: "1"
          limits:
            memory: "4Gi"
            cpu: "2"
