---
- name: Deploy K3s Infrastructure Only (No Kagent)
  hosts: k3s_cluster
  become: yes
  gather_facts: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
    kagent_enabled: false
    ollama_enabled: false

  pre_tasks:
    - name: Update package cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
      when: ansible_os_family == "Debian"

    - name: Install Python3 and pip
      apt:
        name:
          - python3
          - python3-pip
          - python3-apt
        state: present
      when: ansible_os_family == "Debian"

    - name: Install required Python packages
      pip:
        name:
          - kubernetes
          - openshift
          - pyyaml
          - jinja2
        state: present

  roles:
    - role: common
      tags: [common, setup]

    - role: k3s
      tags: [k3s, kubernetes]
      when: node_role is defined

    - role: kubectl-helm
      tags: [kubectl, helm, tools]
      when: node_role == 'master'

  post_tasks:
    - name: Display cluster information
      debug:
        msg:
          - "K3s infrastructure deployment completed!"
          - "Master node: {{ k3s_master_ip }}"
          - "Cluster token: {{ k3s_token }}"
          - "Kubectl and Helm are ready"
          - "No kagent or Ollama installed"
      when: node_role == 'master'

    - name: Save kubeconfig
      copy:
        content: "{{ lookup('file', '/home/' + ansible_user + '/.kube/config') }}"
        dest: "./kubeconfig"
        mode: '0600'
      when: node_role == 'master'

    - name: Display next steps
      debug:
        msg:
          - "Next steps:"
          - "1. Copy kubeconfig to your local machine: scp {{ ansible_user }}@{{ k3s_master_ip }}:./kubeconfig ~/.kube/config"
          - "2. Check cluster status: kubectl get nodes"
          - "3. To install kagent later, set kagent_enabled: true in group_vars/all.yml"
          - "4. Then run: ansible-playbook playbook.yml --tags kagent"
      when: node_role == 'master'
