---
# Ansible Galaxy requirements for kagent deployment
collections:
  - name: kubernetes.core
    version: ">=2.4.0"
  - name: community.general
    version: ">=7.0.0"
  - name: ansible.posix
    version: ">=1.4.0"

roles:
  - name: geerlingguy.docker
    version: "7.0.0"
  - name: geerlingguy.pip
    version: "2.0.0"
